compile:
	g++ -o helloworld hello.world.cpp && ./helloworld

comtime:
	time g++ -o check time.cpp && time ./check

basic:
	g++ -o basic w3_basic.cpp && ./basic

time:
	time g++ -o touch touch.cpp && time ./touch
